import { LabelConfig } from './types';

export const labels: Record<string, LabelConfig> = {
  en: {
    'app.name': 'Burger Fest',
    'app.tagline': 'Track your burger journey',
    'feed.title': 'Burger Feed',
    'feed.empty': 'No burgers yet! Start logging your meals.',
    'feed.loading': 'Loading burgers...',
    'log.title': 'Log Meal',
    'log.photo': 'Take Photo',
    'log.restaurant': 'Restaurant Name',
    'log.rating': 'Rating',
    'log.submit': 'Submit',
    'leaderboard.title': 'Leaderboard',
    'leaderboard.rank': 'Rank',
    'leaderboard.user': 'User',
    'leaderboard.count': 'Burgers',
    'insights.title': 'Insights',
    'profile.title': 'Profile',
    'profile.logout': 'Logout',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.google': 'Continue with Google',
    'auth.github': 'Continue with GitHub',
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.posts': 'Posts',
    'admin.analytics': 'Analytics',
    'error.generic': 'Something went wrong',
    'error.network': 'Network error. Please check your connection.',
    'success.saved': 'Saved successfully',
  },
  es: {
    'app.name': 'Festival de Hamburguesas',
    'app.tagline': 'Rastrea tu viaje de hamburguesas',
    'feed.title': 'Feed de Hamburguesas',
    'feed.empty': '¡Aún no hay hamburguesas! Comienza a registrar tus comidas.',
    'feed.loading': 'Cargando hamburguesas...',
    'log.title': 'Registrar Comida',
    'log.photo': 'Tomar Foto',
    'log.restaurant': 'Nombre del Restaurante',
    'log.rating': 'Calificación',
    'log.submit': 'Enviar',
    'leaderboard.title': 'Clasificación',
    'leaderboard.rank': 'Rango',
    'leaderboard.user': 'Usuario',
    'leaderboard.count': 'Hamburguesas',
    'insights.title': 'Perspectivas',
    'profile.title': 'Perfil',
    'profile.logout': 'Cerrar Sesión',
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.google': 'Continuar con Google',
    'auth.github': 'Continuar con GitHub',
    'admin.dashboard': 'Panel',
    'admin.users': 'Usuarios',
    'admin.posts': 'Publicaciones',
    'admin.analytics': 'Analíticas',
    'error.generic': 'Algo salió mal',
    'error.network': 'Error de red. Por favor verifica tu conexión.',
    'success.saved': 'Guardado exitosamente',
  },
};

export const getLabel = (key: string, locale: string = 'en'): string => {
  return labels[locale]?.[key] || labels.en[key] || key;
};

